# Generated by Django 3.2 on 2022-02-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='product_images')),
                ('price', models.CharField(max_length=100)),
                ('discount_price', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
    ]
