# Generated by Django 3.2 on 2022-02-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afrogulio', '0003_auto_20220217_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='odered',
            new_name='ordered',
        ),
    ]
