# Generated by Django 3.2 on 2022-02-24 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrogulio', '0004_rename_odered_cart_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='deals_images')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
