# Generated by Django 3.2 on 2022-02-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afrogulio', '0005_deals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deals',
            new_name='Deal',
        ),
    ]
